[package]
name = "als-algorithm"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
serde = {version = "1.0.228", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }
